App\Entity\Weather:
  properties:
    temperature:
      - Range:
          min: -100
          max: 200
      - NotBlank:
          groups: ['new', 'edit']
    precipitation:
      - Range:
          min: 0
          max: 100
      - NotBlank:
          groups: ['new', 'edit']
    wind:
      - Range:
          min: 0
          max: 500
      - NotBlank: 
          groups: ['new', 'edit']
    humidity:
      - Range:
          min: 0
          max: 100
      - NotBlank: 
          groups: ['new', 'edit']
    city:
      - NotBlank:
          groups: ['new', 'edit']
    type:
      - NotBlank:
          groups: ['new', 'edit']