App\Entity\City:
  properties:
    name:
      - Length:
          max: 255
      - NotBlank:
          groups: ['new', 'edit']
    country:
      - Length:
          max: 2
      - NotBlank:
          groups: ['new', 'edit']
    latitude:
      - Range:
          min: -90
          max: 90
      - NotBlank:
          groups: ['new', 'edit']
    longitude:
      - Range:
          min: -180
          max: 180
      - NotBlank:
          groups: ['new', 'edit']