App\Entity\City:
  properties:
    name:
      - Length:
          max: 255
      - NotBlank: ~
    country:
      - Length:
          max: 2
      - NotBlank: ~
    latitude:
      - Range:
          min: -90
          max: 90
      - NotBlank: ~
    longitude:
      - Range:
          min: -180
          max: 180
      - NotBlank: ~