#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /{country}/{city}
  controller: App\Controller\WeatherController:cityAction

app_logout:
  path: /logout
  methods: GET